# Generated by Django 4.1.9 on 2023-11-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_profil_jins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='davlat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='kasb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
