# Generated by Django 4.1.9 on 2023-11-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_profil_davlat_profil_email_profil_kasb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('Anotatsiya', models.TextField()),
                ('kalit', models.TextField()),
                ('adabiyot', models.TextField()),
                ('fayl', models.FileField(upload_to='maqola')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.profil')),
            ],
        ),
    ]
